version: '3.4'
services:
  api:
    build:
      context: ./api
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./api:/usr/app/
  db:
    image: postgres:15
    network_mode: host
    volumes: 
      - statle-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statle
      - POSTGRES_USER=statle
      - POSTGRES_PASSWORD=statle
volumes:
  statle-db:
    external: true