version: '3.4'
services:
  api:
    build:
      context: ./api
    network_mode: host
    stdin_open: true
    tty: true
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./api:/usr/app/
  db:
    image: postgres:15
    network_mode: host
    volumes: 
      - statsle-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statsle
      - POSTGRES_USER=statsle
      - POSTGRES_PASSWORD=statsle
  front:
    image: node:18
    network_mode: host
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]
    working_dir: /usr/app
    volumes:
      - ./front:/usr/app/
volumes:
  statsle-db:
    external: true